import Head from 'next/head'
import Banner from './banner/Banner'
import DateSection from './dateSection/DateSection'
import News from './news/News'
import { Place } from './place/Place'
import MoreInfo from './moreInfo/MoreInfo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cris & Angie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <section className="content">
          <News />
          <DateSection />
          <Place />
          <MoreInfo />
        </section>
      </main>
    </>
  )
}
