import Head from 'next/head'
import Banner from '../components/banner/Banner'
import DateSection from '../components/dateSection/DateSection'
import News from '../components/news/News'
import Place from '../components/place/Place'
import MoreInfo from '../components/moreInfo/MoreInfo'
import Confirmation from '../components/confirmation/Confirmation'
import styles from "../styles/index.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Cris & Angie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <section className={styles.content}>
          <Confirmation />
          <News />
          <DateSection />
          <Place />
          <MoreInfo />
        </section>
      </main>
    </>
  )
}
